version: 0.0.{build}
os:
  - Visual Studio 2013
clone_depth: 1
branches:
  only:
    - dcmqi
skip_tags: true
clone_folder: c:\SlicerExecutionModel
install:
  - cinst cmake
configuration:
  - Release
platform:
  - x64
before_build:
  - cmd: cmake --version
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/fedorov/zlib/releases/download/zlib-dcmqi-1.2.3-VS12-Win64-Release/zlib-dcmqi.zip", "C:\zlib-dcmqi.zip")
  - cmd: 7z x C:\zlib-dcmqi.zip -oC:\zlib-install
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/fedorov/DCMTK/releases/download/DCMTK-dcmqi-3.6.1_20160216-VS12-Win64-Release-v0.0.10/DCMTK-dcmqi.zip", "C:\DCMTK-dcmqi.zip")
  - cmd: 7z x C:\DCMTK-dcmqi.zip -oC:\DCMTK-install
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/fedorov/ITK-dcmqi/releases/download/ITK-dcmqi-VS12-Win64-Release-v0.0.12/ITK-dcmqi.zip", "C:\ITK-dcmqi.zip")
  - cmd: 7z x C:\ITK-dcmqi.zip -oC:\ITK-install
  - cmd: mkdir c:\SlicerExecutionModel\SlicerExecutionModel-build
  - cmd: mkdir c:\SlicerExecutionModel\SlicerExecutionModel-install
  - cmd: cd c:\SlicerExecutionModel\SlicerExecutionModel-build
  - cmd: cmake -G "Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_TESTING:BOOL=OFF -DITK_DIR:PATH=C:\ITK-install\lib\cmake\ITK-4.10 -DCMAKE_INSTALL_PREFIX=c:\SlicerExecutionModel\SlicerExecutionModel-install C:\SlicerExecutionModel
build_script:
  - cmd: msbuild SlicerExecutionModel.sln /m
cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
artifacts:
  - path: SlicerExecutionModel-build
    name: SlicerExecutionModel-dcmqi
    type: zip
deploy:
    release: SlicerExecutionModel-dcmqi-VS12-Win64-Release-v$(appveyor_build_version)
    provider: GitHub
    description: 'SlicerExecutionModel packaged by appveyor for dcmqi'
    artifact: SlicerExecutionModel-dcmqi
    auth_token:
      secure: ffHRHxe8buygkDl6kRw4vaNaH/ikYGoDn3TXfZ42cFXq7986houCT7/7qB8o5Vvf
